import Navbar from "@/components/Navbar";
import "./globals.css";
import { Preahvihear } from "next/font/google";
import { LoaderProvider, NextAuthProvider, ReduxProvider } from "./Providers";

const preahvihear = Preahvihear({ subsets: ["latin"], weight: ["400"] });

export const metadata = {
  title: "Todo App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={preahvihear.className}>
        <NextAuthProvider>
          <ReduxProvider>
            <LoaderProvider>
              <Navbar />
              <div className="mt-32">{children}</div>
            </LoaderProvider>
          </ReduxProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
